= DKD Outlet Kit

== Devices

The DKD Outlet operates as local MQTT broker that conforms v3.1.1 specification of the protocol.
With an eye to the limitation of freeware version of the software it may be used as a lightweight replacement of other brokers to handle local equipment and sensors among other production tasks.

=== Authorization

Freeware version of DKD Outlet is auth and encryption free, so any device may connect the instance.

=== Configurations

Everything described in this section is of reference and advisory nature. The embedded configuration covers everything needed for work and doesn't require additional configuring.

==== Netty

netty.epoll:: Linux systems can use epoll instead of nio. To get a performance gain and reduced GC.
See http://netty.io/wiki/native-transports.html for more information
netty.mqtt.message_size:: by default the max size of message is set at 8092 bytes.
See http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180836
for more information about payload size specs.

.java options
----
-Dnetty.epoll=true
-Dnetty.mqtt.message_size=8092
----


== Logging
=== Custom config

  -Dlogback.configurationFile=$(pwd)/logback.xml

.logback.xml
[source,xml]
----
<configuration scan="false">
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n</pattern>
        </encoder>

        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>
    </appender>

    <root level="WARN">
        <appender-ref ref="STDOUT"/>
    </root>
    <root level="ERROR">
        <appender-ref ref="STDOUT"/>
    </root>
    <root level="INFO">
        <appender-ref ref="STDOUT"/>
    </root>

    <logger name="org.eclipse.jetty" level="INFO"/>
    <logger name="dkd-outlet" level="INFO"/>
</configuration>
----

== License

The DKD Outlet software is Freemium and doesn’t require any additional activities to be done to get its components working. The software distributes 'as is' in binary form and is free of charge. However, shareware is a proprietary software kind and does not imply any additional warranty, source code access, passing out any intellectual properties rights among other conditions. In all and any other parts therein that does not confront the previously mentioned, the DKD Outlet software is covered by Commercial Licence Agreement for DKD and/or DKDHUB products that placed aside at this repository.

== Copyrights

&copy; 2021-2023 Fern Flower Lab and affiliates